/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.TPPredador;
import model.VampiroCriador;

/**
 *
 * @author @Ana
 */
public class CadastroVampiro1JD extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroVampiro1JD.class.getName());

    /**
     * Creates new form CadastroVampiroJD
     */
    public CadastroVampiro1JD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCla = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        txtCla = new javax.swing.JTextField();
        lblConceito = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        lblCriador = new javax.swing.JLabel();
        txtConceito = new javax.swing.JTextField();
        cmbCriador = new javax.swing.JComboBox<>();
        btnInfoConceito = new javax.swing.JButton();
        btnCriar = new javax.swing.JButton();
        btnInfoCla = new javax.swing.JButton();
        lblPredador = new javax.swing.JLabel();
        cmbPredador = new javax.swing.JComboBox<>();
        btnAvancar = new javax.swing.JButton();
        btnInfoPredador = new javax.swing.JButton();
        btnInfoCriador = new javax.swing.JButton();
        lblDisciplinas = new javax.swing.JLabel();
        btnInfoDisciplinas = new javax.swing.JButton();
        lblDisciplina1 = new javax.swing.JLabel();
        lblDisciplina2 = new javax.swing.JLabel();
        lblDisciplina3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel1.setText("Cadastro de VAMPIRO");

        lblNome.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblNome.setText("Nome:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblCla.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblCla.setText("Clã:");

        lblIdade.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblIdade.setText("Idade:");

        txtCla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaActionPerformed(evt);
            }
        });

        lblConceito.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblConceito.setText("Conceito:");

        txtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeActionPerformed(evt);
            }
        });

        lblCriador.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblCriador.setText("Criador:");

        txtConceito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConceitoActionPerformed(evt);
            }
        });

        btnInfoConceito.setText("Info");

        btnCriar.setText("Criar");

        btnInfoCla.setText("Info");
        btnInfoCla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoClaActionPerformed(evt);
            }
        });

        lblPredador.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblPredador.setText("Tipo Predador:");

        btnAvancar.setText("Avançar");

        btnInfoPredador.setText("Info");
        btnInfoPredador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoPredadorActionPerformed(evt);
            }
        });

        btnInfoCriador.setText("Info");

        lblDisciplinas.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblDisciplinas.setText("Disciplinas:");

        btnInfoDisciplinas.setText("Info");
        btnInfoDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoDisciplinasActionPerformed(evt);
            }
        });

        lblDisciplina1.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblDisciplina1.setText("Sem Disciplina");

        lblDisciplina2.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblDisciplina2.setText("Sem Disciplina");

        lblDisciplina3.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblDisciplina3.setText("Sem Disciplina");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCla)
                            .addComponent(lblNome)
                            .addComponent(lblIdade)
                            .addComponent(lblConceito)
                            .addComponent(lblCriador)
                            .addComponent(lblPredador)
                            .addComponent(lblDisciplinas, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAvancar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNome)
                            .addComponent(txtCla)
                            .addComponent(txtIdade)
                            .addComponent(txtConceito)
                            .addComponent(cmbCriador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPredador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDisciplina1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDisciplina2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDisciplina3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInfoCriador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCriar))
                            .addComponent(btnInfoCla)
                            .addComponent(btnInfoPredador)
                            .addComponent(btnInfoConceito)
                            .addComponent(btnInfoDisciplinas))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCla)
                    .addComponent(txtCla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInfoCla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdade)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConceito)
                    .addComponent(txtConceito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInfoConceito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCriador)
                    .addComponent(cmbCriador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCriar)
                    .addComponent(btnInfoCriador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPredador)
                    .addComponent(cmbPredador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInfoPredador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisciplinas)
                    .addComponent(btnInfoDisciplinas)
                    .addComponent(lblDisciplina1)
                    .addComponent(lblDisciplina2)
                    .addComponent(lblDisciplina3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAvancar)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtClaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaActionPerformed

    private void txtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeActionPerformed

    private void txtConceitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConceitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConceitoActionPerformed

    private void btnInfoPredadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoPredadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfoPredadorActionPerformed

    private void btnInfoClaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoClaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfoClaActionPerformed

    private void btnInfoDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoDisciplinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfoDisciplinasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroVampiro1JD().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnInfoCla;
    private javax.swing.JButton btnInfoConceito;
    private javax.swing.JButton btnInfoCriador;
    private javax.swing.JButton btnInfoDisciplinas;
    private javax.swing.JButton btnInfoPredador;
    private javax.swing.JComboBox<VampiroCriador> cmbCriador;
    private javax.swing.JComboBox<TPPredador> cmbPredador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCla;
    private javax.swing.JLabel lblConceito;
    private javax.swing.JLabel lblCriador;
    private javax.swing.JLabel lblDisciplina1;
    private javax.swing.JLabel lblDisciplina2;
    private javax.swing.JLabel lblDisciplina3;
    private javax.swing.JLabel lblDisciplinas;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPredador;
    private javax.swing.JTextField txtCla;
    private javax.swing.JTextField txtConceito;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
