/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import model.Clan;
import model.Estado;
import model.Humano;
import model.PersonagemVamp;
import model.TPPredador;
import model.VampiroCriador;
import model.dao.HumanoDAO;
import model.dao.VampiroCriadorDAO;

/**
 *
 * @author @Ana
 */
public class CadastroVampiro1JD extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroVampiro1JD.class.getName());
    private PersonagemVamp personagem;
    VampiroCriadorDAO daoCriador;
    HumanoDAO daoHumano;

    /**
     * Creates new form CadastroVampiroJD
     */
    public CadastroVampiro1JD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        daoCriador = new VampiroCriadorDAO();
        daoHumano = new HumanoDAO();
        loadCla();
        loadCriador();
        loadHumano();
        loadPredador();

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCla = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblConceito = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        lblCriador = new javax.swing.JLabel();
        txtConceito = new javax.swing.JTextField();
        cmbCriador = new javax.swing.JComboBox<>();
        lblPredador = new javax.swing.JLabel();
        cmbPredador = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        lblDisciplinas = new javax.swing.JLabel();
        lblDisciplina1 = new javax.swing.JLabel();
        lblDisciplina2 = new javax.swing.JLabel();
        lblDisciplina3 = new javax.swing.JLabel();
        cmbCla = new javax.swing.JComboBox<>();
        cmbHumano = new javax.swing.JComboBox<>();
        lblHumano = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        lblTitulo.setText("Cadastro de VAMPIRO");

        lblNome.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblNome.setText("Nome:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblCla.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblCla.setText("Clã:");

        lblIdade.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblIdade.setText("Idade:");

        lblConceito.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblConceito.setText("Conceito:");

        txtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeActionPerformed(evt);
            }
        });

        lblCriador.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblCriador.setText("Criador:");

        txtConceito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConceitoActionPerformed(evt);
            }
        });

        lblPredador.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblPredador.setText("Tipo Predador:");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lblDisciplinas.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblDisciplinas.setText("Disciplinas:");

        lblDisciplina1.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblDisciplina1.setText("Sem Disciplina");

        lblDisciplina2.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblDisciplina2.setText("Sem Disciplina");

        lblDisciplina3.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblDisciplina3.setText("Sem Disciplina");

        cmbCla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClaActionPerformed(evt);
            }
        });

        lblHumano.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblHumano.setText("Humano Conhecido:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCla)
                                .addComponent(lblNome)
                                .addComponent(lblIdade)
                                .addComponent(lblConceito)
                                .addComponent(lblCriador)
                                .addComponent(lblPredador)
                                .addComponent(lblDisciplinas, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblHumano))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNome)
                            .addComponent(txtIdade)
                            .addComponent(txtConceito)
                            .addComponent(cmbCriador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPredador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDisciplina1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDisciplina2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDisciplina3))
                            .addComponent(cmbHumano, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCla)
                    .addComponent(cmbCla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdade)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConceito)
                    .addComponent(txtConceito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCriador)
                    .addComponent(cmbCriador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPredador)
                    .addComponent(cmbPredador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbHumano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHumano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisciplinas)
                    .addComponent(lblDisciplina1)
                    .addComponent(lblDisciplina2)
                    .addComponent(lblDisciplina3))
                .addGap(33, 33, 33)
                .addComponent(btnCadastrar)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeActionPerformed

    private void txtConceitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConceitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConceitoActionPerformed

    private void cmbClaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClaActionPerformed
       Clan clan = (Clan) cmbCla.getSelectedItem();

    if (clan != null) {
        lblDisciplina1.setText(clan.getDisciplina1());
        lblDisciplina2.setText(clan.getDisciplina2());
        lblDisciplina3.setText(clan.getDisciplina3());
    }
    }//GEN-LAST:event_cmbClaActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            if (personagem == null) {
                personagem = new PersonagemVamp();
            }

            personagem.setNome(txtNome.getText());
            personagem.setClan((Clan) cmbCla.getSelectedItem());
            personagem.setIdade(Integer.parseInt(txtIdade.getText()));
            personagem.setConceito(txtConceito.getText());
            personagem.setCriador((VampiroCriador) cmbCriador.getSelectedItem());
            personagem.setPredador((TPPredador) cmbPredador.getSelectedItem()); // se for enum ou objeto
            personagem.setHumano((Humano) cmbHumano.getSelectedItem());

            JOptionPane.showMessageDialog(this, "Cadastrado com sucesso!");
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Ocorreu um erro inesperado:\n" + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void loadCla() {
        cmbCla.removeAllItems();
//        for(Modelo obj: Modelo.values()){
//            cmbModelo.addItem(obj);
//        }
        cmbCla.removeAllItems();

        List<Clan> estados = new ArrayList<>(Arrays.asList(Clan.values()));

        estados.forEach(e -> cmbCla.addItem(e));
    }

    public PersonagemVamp getPersonagem() {
        return personagem;
    }
    
    public void setPersonagem(PersonagemVamp personagem) {
        this.personagem = personagem;
        txtNome.setText(personagem.getNome());
        cmbCla.setSelectedItem(personagem.getClan());
        txtIdade.setText(String.valueOf(personagem.getIdade()));
        txtConceito.setText(personagem.getConceito());
        cmbCriador.setSelectedItem(personagem.getCriador());
        cmbPredador.setSelectedItem(personagem.getPredador());
        cmbHumano.setSelectedItem(personagem.getHumano());
    }
    private void loadPredador() {
        cmbPredador.removeAllItems();
//        for(Modelo obj: Modelo.values()){
//            cmbModelo.addItem(obj);
//        }
        cmbPredador.removeAllItems();

        List<TPPredador> estados = new ArrayList<>(Arrays.asList(TPPredador.values()));

        estados.forEach(e -> cmbPredador.addItem(e));
    }
    
    

    public void loadCriador() {
        for (VampiroCriador obj : daoCriador.listaVampirosCriadores()) {
            cmbCriador.addItem(obj);
        }
    }

    public void loadHumano() {
        for (Humano obj : daoHumano.listaHumanos()) {
            cmbHumano.addItem(obj);
        }
    }

    /**
     * 1
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new CadastroVampiro1JD().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox<Clan> cmbCla;
    private javax.swing.JComboBox<VampiroCriador> cmbCriador;
    private javax.swing.JComboBox<Humano> cmbHumano;
    private javax.swing.JComboBox<TPPredador> cmbPredador;
    private javax.swing.JLabel lblCla;
    private javax.swing.JLabel lblConceito;
    private javax.swing.JLabel lblCriador;
    private javax.swing.JLabel lblDisciplina1;
    private javax.swing.JLabel lblDisciplina2;
    private javax.swing.JLabel lblDisciplina3;
    private javax.swing.JLabel lblDisciplinas;
    private javax.swing.JLabel lblHumano;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPredador;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtConceito;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
